workflows:
  hackathlone-workflow:
    name: HackAthlone Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        SUPABASE_URL: $SUPABASE_URL
        SUPABASE_ANON_KEY: $SUPABASE_ANON_KEY
        # Base64 encoded google-services.json content
        GOOGLE_SERVICES_JSON: $GOOGLE_SERVICES_JSON

    scripts:
      - name: Get Flutter packages
        script: flutter packages get

      - name: Setup Firebase configuration
        script: |
          echo "🔥 Creating google-services.json for Android..."
          mkdir -p android/app
          cat > android/app/google-services.json << 'EOF'
          {
            "project_info": {
              "project_number": "1005959368725",
              "project_id": "hackathlone-app",
              "storage_bucket": "hackathlone-app.firebasestorage.app"
            },
            "client": [
              {
                "client_info": {
                  "mobilesdk_app_id": "1:1005959368725:android:864d092dff42fbfa65fe1c",
                  "android_client_info": {
                    "package_name": "com.hackathlone.hackathlone_app"
                  }
                },
                "oauth_client": [],
                "api_key": [
                  {
                    "current_key": "AIzaSyDeS1vyZXnUhL8Av99AB_bxFsEmTIi0bAc"
                  }
                ],
                "services": {
                  "appinvite_service": {
                    "other_platform_oauth_client": []
                  }
                }
              }
            ],
            "configuration_version": "1"
          }
          EOF
          echo "✅ google-services.json created successfully"
          ls -la android/app/google-services.json

      - name: Generate code (Hive adapters)
        script: |
          chmod +x scripts/ci/generate.sh
          scripts/ci/generate.sh

      - name: Flutter analyze
        script: flutter analyze --no-fatal-infos

      - name: Flutter test
        script: flutter test
        ignore_failure: true

      - name: Build APK
        script: flutter build apk --release --no-obfuscate --no-shrink

 - name: Build iOS Device & Simulator
        script: |
          if [ "$CM_BRANCH" = "main" ]; then
            echo "📱 Building iOS Device app..."
            flutter build ios --release --no-codesign
            
            echo "🖥️ Building iOS Simulator app..."
            flutter build ios --simulator --release --no-codesign
            
            echo "📦 Creating iOS artifacts..."
            mkdir -p build/ios/ipa
            
            cd build/ios/iphoneos
            mkdir -p Payload
            cp -r Runner.app Payload/
            zip -r ../ipa/Runner-device.ipa Payload/
            rm -rf Payload
            cd ../../..
            
            if [ -d "build/ios/iphonesimulator/Runner.app" ]; then
              echo "✅ Found simulator build, creating ZIP..."
              cd build/ios/iphonesimulator
              zip -r ../../ipa/Runner-simulator.zip Runner.app
              cd ../../..
            else
              echo "❌ Simulator build not found—check build logs for errors."
              exit 1 
            fi
        

    artifacts:
      - build/**/outputs/**/*.apk
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.zip
      - build/ios/iphoneos/Runner.app

    publishing:
      email:
        recipients:
          - sheanhans03@gmail.com
        notify:
          success: true
          failure: true
