workflows:
  hackathlone-workflow:
    name: HackAthlone Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        SUPABASE_URL: $SUPABASE_URL
        SUPABASE_ANON_KEY: $SUPABASE_ANON_KEY
        # Base64 encoded google-services.json content
        GOOGLE_SERVICES_JSON: $GOOGLE_SERVICES_JSON

    scripts:
      - name: Get Flutter packages
        script: flutter packages get

      - name: Setup Firebase configuration
        script: |
          echo "ðŸ”¥ Creating google-services.json for Android..."
          mkdir -p android/app
          cat > android/app/google-services.json << 'EOF'
          {
            "project_info": {
              "project_number": "1005959368725",
              "project_id": "hackathlone-app",
              "storage_bucket": "hackathlone-app.firebasestorage.app"
            },
            "client": [
              {
                "client_info": {
                  "mobilesdk_app_id": "1:1005959368725:android:864d092dff42fbfa65fe1c",
                  "android_client_info": {
                    "package_name": "com.hackathlone.hackathlone_app"
                  }
                },
                "oauth_client": [],
                "api_key": [
                  {
                    "current_key": "AIzaSyDeS1vyZXnUhL8Av99AB_bxFsEmTIi0bAc"
                  }
                ],
                "services": {
                  "appinvite_service": {
                    "other_platform_oauth_client": []
                  }
                }
              }
            ],
            "configuration_version": "1"
          }
          EOF
          echo "âœ… google-services.json created successfully"
          ls -la android/app/google-services.json

      - name: Generate code (Hive adapters)
        script: |
          chmod +x scripts/ci/generate.sh
          scripts/ci/generate.sh

      - name: Flutter analyze
        script: flutter analyze --no-fatal-infos

      - name: Flutter test
        script: flutter test
        ignore_failure: true

      - name: Build APK
        script: flutter build apk --release --no-obfuscate --no-shrink

      - name: Build iOS Device & Simulator
        script: |
          if [ "$CM_BRANCH" = "main" ]; then
            echo "ðŸ“± Building iOS Device app..."
            flutter build ios --no-codesign
            
            echo "ðŸ–¥ï¸ Building iOS Simulator app..."
            cd ios
            xcodebuild -workspace Runner.xcworkspace -scheme Runner -configuration Release -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14' build CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
            cd ..
            
            echo "ðŸ“¦ Creating iOS artifacts..."
            mkdir -p build/ios/ipa
            
            # Create device IPA (for TestFlight/App Store)
            cd build/ios/iphoneos
            mkdir -p Payload
            cp -r Runner.app Payload/
            zip -r ../ipa/Runner-device.ipa Payload/
            rm -rf Payload
            cd ../../..
            
            # Create simulator ZIP for Appetize.io
            if [ -d "ios/build/Release-iphonesimulator/Runner.app" ]; then
              echo "âœ… Found simulator build, creating ZIP..."
              cd ios/build/Release-iphonesimulator
              zip -r ../../../build/ios/ipa/Runner-simulator.zip Runner.app
              cd ../../..
            else
              echo "âš ï¸ Simulator build not found, using device build as fallback"
              cd build/ios/iphoneos
              zip -r ../ipa/Runner-simulator.zip Runner.app
              cd ../../..
            fi
            
            echo "âœ… iOS builds created successfully:"
            echo "ðŸ“± Device IPA: build/ios/ipa/Runner-device.ipa (for TestFlight/App Store)"
            echo "ðŸ–¥ï¸ Simulator ZIP: build/ios/ipa/Runner-simulator.zip (for Appetize.io)"
            ls -la build/ios/ipa/
          else
            echo "Skipping iOS build for non-main branch"
          fi

    artifacts:
      - build/**/outputs/**/*.apk
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.zip
      - build/ios/iphoneos/Runner.app

    publishing:
      email:
        recipients:
          - sheanhans03@gmail.com
        notify:
          success: true
          failure: true
