// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYocZeti9go-UIFKjJIIK5Fa7yNnvxovE',
    appId: '1:1005959368725:web:749db75ba2f4d5a565fe1c',
    messagingSenderId: '1005959368725',
    projectId: 'hackathlone-app',
    authDomain: 'hackathlone-app.firebaseapp.com',
    storageBucket: 'hackathlone-app.firebasestorage.app',
    measurementId: 'G-WT9EVWBND2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeS1vyZXnUhL8Av99AB_bxFsEmTIi0bAc',
    appId: '1:1005959368725:android:864d092dff42fbfa65fe1c',
    messagingSenderId: '1005959368725',
    projectId: 'hackathlone-app',
    storageBucket: 'hackathlone-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNORKJrUusL3ACwKVSNdlwjEQBArJwNyQ',
    appId: '1:1005959368725:ios:714dfdab0d9e3c3965fe1c',
    messagingSenderId: '1005959368725',
    projectId: 'hackathlone-app',
    storageBucket: 'hackathlone-app.firebasestorage.app',
    iosBundleId: 'com.hackathlone.hackathloneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNORKJrUusL3ACwKVSNdlwjEQBArJwNyQ',
    appId: '1:1005959368725:ios:714dfdab0d9e3c3965fe1c',
    messagingSenderId: '1005959368725',
    projectId: 'hackathlone-app',
    storageBucket: 'hackathlone-app.firebasestorage.app',
    iosBundleId: 'com.hackathlone.hackathloneApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYocZeti9go-UIFKjJIIK5Fa7yNnvxovE',
    appId: '1:1005959368725:web:6bd01b532d933f8a65fe1c',
    messagingSenderId: '1005959368725',
    projectId: 'hackathlone-app',
    authDomain: 'hackathlone-app.firebaseapp.com',
    storageBucket: 'hackathlone-app.firebasestorage.app',
    measurementId: 'G-WX02RX7YGL',
  );
}
